server:
  port: 8081

spring:
  application:
    name: order-api
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: order
    password: order_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
