spring.application.name=order-api

spring.datasource.url=jdbc:postgresql://localhost:5432/apisdb
spring.datasource.username=apis_user
spring.datasource.password=apis_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=localhost:9092
