spring.application.name=order-api

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=order_user
spring.datasource.password=order_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.kafka.bootstrap-servers=localhost:9092
