apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-api
  labels:
    app: invoice-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-api
  template:
    metadata:
      labels:
        app: invoice-api
    spec:
      containers:
      - name: invoice-api
        image: invoice-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-api
spec:
  type: ClusterIP
  selector:
    app: invoice-api
  ports:
  - port: 8080
    targetPort: 8080
