apiVersion: v1
kind: Service
metadata:
  labels:
    app: invoice-service
  name: invoice-service
  namespace: orderslab
spec:
  type: LoadBalancer
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8080
  selector:
    app: invoice-service
