apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafbat-ui
  name: kafbat-ui
  namespace: orderslab
spec:
  type: LoadBalancer
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8080
  selector:
    app: kafbat-ui
