apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: apis_password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-api:5432/apisdb
            - name: SPRING_DATASOURCE_USERNAME
              value: apis_user
          image: payment-service
          imagePullPolicy: Never
          name: payment-api
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
