apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-api
  name: postgres-api
  namespace: orderslab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-api
  template:
    metadata:
      labels:
        app: postgres-api
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: apis_admin_password
            - name: POSTGRES_USER
              value: apis_admin
          image: postgres:15-alpine
          name: postgres-api
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-init
          configMap:
            name: postgres-api-init
      restartPolicy: Always
