ALTER TABLE invoices ADD COLUMN source_event_id UUID;

CREATE UNIQUE INDEX ux_invoices_source_event_id ON invoices (source_event_id);

CREATE UNIQUE INDEX ux_invoices_order_id_from_event ON invoices (order_id)
    WHERE source_event_id IS NOT NULL;

CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    event_type VARCHAR(50) NOT NULL,
    topic VARCHAR(100) NOT NULL,
    aggregate_id UUID NOT NULL,
    payload TEXT NOT NULL,
    trace_id VARCHAR(64),
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
