name: order-api

on:
  push:
    branches: [develop, main]
    tags:
      - 'order-api-v*.*.*'
  pull_request:
    branches: [develop, main]
    paths:
      - 'order-api/**'
      - '.github/workflows/order-api.yml'
      - '.github/workflows/service-ci.yml'

jobs:
  ci:
    uses: ./.github/workflows/service-ci.yml
    with:
      service-name: order-api
